name: Run Crossfit Registration Script

on:
  workflow_dispatch:
  schedule:
    - cron: "2 23 * * 6" # Every Saturday 23:02 UTC (Sunday 00:02 GMT+1)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true  # skip Puppeteerâ€™s Chromium

      # Launch Chrome (headful) in the background
      - uses: browser-actions/puppeteer-headful@v1

      # Run your Node script with the environment variable
      - name: Run Puppeteer script
        run: node login-and-register.js
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
