name: Run Script on Sunday at 00:02 AM (GMT+1)

on:
  schedule:
    - cron: "2 23 * * 6"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Install Chromium
        run: npx puppeteer browsers install chromium

      - name: Run script
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: node login-and-register.js
