name: Run Script on Sunday at 00:02 AM (GMT+1)

on:
  schedule:
    # Cron-schema: Elke zaterdag 23:02 UTC (wat overeenkomt met 00:02 GMT+1 op zondag)
    - cron: "2 23 * * 6"
  workflow_dispatch: # Optioneel: handmatig starten via de GitHub interface
    inputs: {}

jobs:
  run-script:
    runs-on: ubuntu-latest # Gebruik een Linux-machine van GitHub
    steps:
      # Check de repository code uit
      - name: Checkout code
        uses: actions/checkout@v3

      # Stel Node.js in
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Node.js versie

      # Installeer npm dependencies
      - name: Install dependencies
        run: npm install

      # Voer het script uit
      - name: Run script
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: node login-and-register.js
